services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: avalon_backend
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./Logs:/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: https://avalon.tom-nguyen.ca
    container_name: avalon_frontend
    restart: always
    ports:
      - "3002:80"
